---
# tasks file for delete_old_files
- name: Ansible delete files older than "{{ number_of_days }}" days
  find:
    paths: "{{ root_directory }}"
    age: "{{ number_of_days }}"
    recurse: yes
  register: files_to_delete

#- name: Print return information from the previous task
#  ansible.builtin.debug:
#    var: "{{item}}"
#  with_items: "{{ files_to_delete.files }}"


- name: Ansible remove files older than a date example
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"